### ISSUE TITLE
[RecipeOrganizer] Cannot implicitly convert type 'StardewValley.Network.NetStringDictionary<int, Netcode.NetInt>' to 'System.Collections.Generic.Dictionary<string, int>'

### ISSUE THREAD

**Issue by mathuin** [musbah/StardewValleyMods#3]
I'm a big fan of your bundle tooltip mod, and wanted to try out your recipe organizer.  When I tried to compile it from source, I got the error mentioned above on line 60 of SortRecipes(), which looks like this:

            Dictionary<string, int> farmerRecipes = Game1.player.cookingRecipes;

I've no experience with C# in general or SDV mods in particular so I don't know how to fix the issue, or I'd send a pull request.  I am building on Ubuntu Linux 16.04.4 LTS using monodevelop 7.5 if that helps.

**Comment by musbah** [comment]
hey, thank you for the compliments. The recipe organizer was never finished, it was just an experimental thing that I was trying out. Even if you do succeed in compiling it, you really won't see much.

Thanks a lot for being interested and trying though.
