### ISSUE TITLE
BundleToolTips not compatible with 1.3.32

### ISSUE THREAD

**Issue by Stevoisiak** [musbah/StardewValleyMods#4]
The BundleToolTips mod is not compatible with Stardew Valley 1.3.32 (released November 19, 2018). SMAPI gives the following error:

> Community Bundle Item Tooltip 1.1 because it's no longer compatible. Please check for a new version at https://mods.smapi.io.

**Comment by musbah** [comment]
Oh, I never noticed this issue. Fixed this at the beginning of December (just needed to recompile with the newest SMAPI). I do appreciate the heads up though, thank you.
